//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreedomLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreedomLogic.Resources.AccountRes", typeof(AccountRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created.
        /// </summary>
        public static string FieldCreationDate {
            get {
                return ResourceManager.GetString("FieldCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current display name.
        /// </summary>
        public static string FieldCurrentDisplayName {
            get {
                return ResourceManager.GetString("FieldCurrentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string FieldCurrentPassword {
            get {
                return ResourceManager.GetString("FieldCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string FieldDisplayName {
            get {
                return ResourceManager.GetString("FieldDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string FieldEmail {
            get {
                return ResourceManager.GetString("FieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM3: Administrator.
        /// </summary>
        public static string FieldGMLevelAdmin {
            get {
                return ResourceManager.GetString("FieldGMLevelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM2: Game master.
        /// </summary>
        public static string FieldGMLevelGM {
            get {
                return ResourceManager.GetString("FieldGMLevelGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMLevel / Game account access.
        /// </summary>
        public static string FieldGMLevelList {
            get {
                return ResourceManager.GetString("FieldGMLevelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM1: Moderator / Storyteller.
        /// </summary>
        public static string FieldGMLevelModerator {
            get {
                return ResourceManager.GetString("FieldGMLevelModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM0: Player.
        /// </summary>
        public static string FieldGMLevelPlayer {
            get {
                return ResourceManager.GetString("FieldGMLevelPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New display name.
        /// </summary>
        public static string FieldNewDisplayName {
            get {
                return ResourceManager.GetString("FieldNewDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email address.
        /// </summary>
        public static string FieldNewEmail {
            get {
                return ResourceManager.GetString("FieldNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string FieldNewPassword {
            get {
                return ResourceManager.GetString("FieldNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string FieldPassword {
            get {
                return ResourceManager.GetString("FieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string FieldRememberMe {
            get {
                return ResourceManager.GetString("FieldRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter password.
        /// </summary>
        public static string FieldRepeatPassword {
            get {
                return ResourceManager.GetString("FieldRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Account.
        /// </summary>
        public static string FieldTargetAccount {
            get {
                return ResourceManager.GetString("FieldTargetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target account password.
        /// </summary>
        public static string FieldTargetAccountPassword {
            get {
                return ResourceManager.GetString("FieldTargetAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target account username.
        /// </summary>
        public static string FieldTargetAccountUsername {
            get {
                return ResourceManager.GetString("FieldTargetAccountUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string FieldUsername {
            get {
                return ResourceManager.GetString("FieldUsername", resourceCulture);
            }
        }
    }
}
