//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreedomLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreedomLogic.Resources.ErrorRes", typeof(ErrorRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in..
        /// </summary>
        public static string ErrAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("ErrAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sent a bad/malformed request to the server, which was rejected..
        /// </summary>
        public static string ErrBadRequest {
            get {
                return ResourceManager.GetString("ErrBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while processing your request. You should contact the developers about this issue, including information on how to reproduce this problem..
        /// </summary>
        public static string ErrDefault {
            get {
                return ResourceManager.GetString("ErrDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error on the server occurred while processing your request. You should contact the developers about this issue, including information on how to reproduce this problem..
        /// </summary>
        public static string ErrInternalServer {
            get {
                return ResourceManager.GetString("ErrInternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested page/resource was not found..
        /// </summary>
        public static string ErrNotFound {
            get {
                return ResourceManager.GetString("ErrNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have required permissions to view this page..
        /// </summary>
        public static string ErrUnauthorized {
            get {
                return ResourceManager.GetString("ErrUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target account is full (no available character slots)..
        /// </summary>
        public static string ModelErrCharacterTransferAccountFull {
            get {
                return ResourceManager.GetString("ModelErrCharacterTransferAccountFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target account was not found under such username..
        /// </summary>
        public static string ModelErrCharacterTransferAccountNotFound {
            get {
                return ResourceManager.GetString("ModelErrCharacterTransferAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected character does not exist (was it deleted before submit?)..
        /// </summary>
        public static string ModelErrCharacterTransferCharDoesNotExist {
            get {
                return ResourceManager.GetString("ModelErrCharacterTransferCharDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected character does not belong to you (was it already transferred?)..
        /// </summary>
        public static string ModelErrCharacterTransferInvalidOwner {
            get {
                return ResourceManager.GetString("ModelErrCharacterTransferInvalidOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password for the target account..
        /// </summary>
        public static string ModelErrCharacterTransferInvalidPassword {
            get {
                return ResourceManager.GetString("ModelErrCharacterTransferInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name &quot;{0}&quot; is already taken..
        /// </summary>
        public static string ModelErrDisplayNameTaken {
            get {
                return ResourceManager.GetString("ModelErrDisplayNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset token has is either invalid or expired..
        /// </summary>
        public static string ModelErrInvalidPasswordResetToken {
            get {
                return ResourceManager.GetString("ModelErrInvalidPasswordResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no characters to transfer..
        /// </summary>
        public static string ModelErrNoCharactersToTransfer {
            get {
                return ResourceManager.GetString("ModelErrNoCharactersToTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string ModelErrPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("ModelErrPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have this display name..
        /// </summary>
        public static string ModelErrSameDisplayName {
            get {
                return ResourceManager.GetString("ModelErrSameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &quot;{0}&quot; is already taken..
        /// </summary>
        public static string ModelErrUsernameTaken {
            get {
                return ResourceManager.GetString("ModelErrUsernameTaken", resourceCulture);
            }
        }
    }
}
