//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreedomLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreedomLogic.Resources.ServerRes", typeof(ServerRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bnetserver path.
        /// </summary>
        public static string FieldBnetServerPath {
            get {
                return ResourceManager.GetString("FieldBnetServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bnetserver process id.
        /// </summary>
        public static string FieldBnetServerPid {
            get {
                return ResourceManager.GetString("FieldBnetServerPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bnetserver status.
        /// </summary>
        public static string FieldBnetServerStatus {
            get {
                return ResourceManager.GetString("FieldBnetServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search type.
        /// </summary>
        public static string FieldEnumSearchType {
            get {
                return ResourceManager.GetString("FieldEnumSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by id.
        /// </summary>
        public static string FieldSearchId {
            get {
                return ResourceManager.GetString("FieldSearchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server directory path.
        /// </summary>
        public static string FieldServerDirectoryPath {
            get {
                return ResourceManager.GetString("FieldServerDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login server down (world server is up, however).
        /// </summary>
        public static string FieldServerStatusLoginDown {
            get {
                return ResourceManager.GetString("FieldServerStatusLoginDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline (login and world servers are down).
        /// </summary>
        public static string FieldServerStatusOffline {
            get {
                return ResourceManager.GetString("FieldServerStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online (login and world servers are up).
        /// </summary>
        public static string FieldServerStatusOnline {
            get {
                return ResourceManager.GetString("FieldServerStatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World server down (login server is up, however).
        /// </summary>
        public static string FieldServerStatusWorldDown {
            get {
                return ResourceManager.GetString("FieldServerStatusWorldDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World server is currently loading/starting up.
        /// </summary>
        public static string FieldServerStatusWorldLoading {
            get {
                return ResourceManager.GetString("FieldServerStatusWorldLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldserver path.
        /// </summary>
        public static string FieldWorldServerPath {
            get {
                return ResourceManager.GetString("FieldWorldServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldserver process id.
        /// </summary>
        public static string FieldWorldServerPid {
            get {
                return ResourceManager.GetString("FieldWorldServerPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldserver status.
        /// </summary>
        public static string FieldWorldServerStatus {
            get {
                return ResourceManager.GetString("FieldWorldServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature display id.
        /// </summary>
        public static string ListItemEnumSearchTypeCreatureDisplayId {
            get {
                return ResourceManager.GetString("ListItemEnumSearchTypeCreatureDisplayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature entry id.
        /// </summary>
        public static string ListItemEnumSearchTypeCreatureEntryId {
            get {
                return ResourceManager.GetString("ListItemEnumSearchTypeCreatureEntryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameobject display id.
        /// </summary>
        public static string ListItemEnumSearchTypeGameobjectDisplayId {
            get {
                return ResourceManager.GetString("ListItemEnumSearchTypeGameobjectDisplayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameobject entry id.
        /// </summary>
        public static string ListItemEnumSearchTypeGameobjectEntryId {
            get {
                return ResourceManager.GetString("ListItemEnumSearchTypeGameobjectEntryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameobject name.
        /// </summary>
        public static string ListItemEnumSearchTypeGameobjectName {
            get {
                return ResourceManager.GetString("ListItemEnumSearchTypeGameobjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item display id.
        /// </summary>
        public static string ListItemEnumSearchTypeItemDisplayId {
            get {
                return ResourceManager.GetString("ListItemEnumSearchTypeItemDisplayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item entry id.
        /// </summary>
        public static string ListItemEnumSearchTypeItemEntryId {
            get {
                return ResourceManager.GetString("ListItemEnumSearchTypeItemEntryId", resourceCulture);
            }
        }
    }
}
